server:
  port: 8084
  servlet:
    context-path: /notifications
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: notification-service
  profiles:
    active: ""
  datasource:
    url: "jdbc:mysql://localhost:3306/chat-realtime_notification"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

    topic:
      name: notifications_topics
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 360000 # in seconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      shutdown:
        access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "notification"
    description: "Notification service application"
    version: "1.0.0"


logging:
  level:
    org.springframework.web: DEBUG