server:
    port: 8888

app:
    api-prefix: /api

spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        routes:
          - id: identity-service
            uri:
              http://localhost:8080
            predicates:
              - Path=${app.api-prefix}/identity/**
            filters:
              - StripPrefix=1
          - id: chat-service
            uri:
              http://localhost:8081
            predicates:
              - Path=${app.api-prefix}/chat/**
            filters:
              - StripPrefix=1
          - id: friend-service
            uri:
              http://localhost:8083
            predicates:
              - Path=${app.api-prefix}/friend/**
            filters:
              - StripPrefix=1
          - id: notification-service
            uri:
              http://localhost:8084
            predicates:
              - Path=${app.api-prefix}/notifications/**
            filters:
              - StripPrefix=1