server:
  port: 8083
  servlet:
    context-path: /friend

spring:
  application:
    name: friend-service
  profiles:
    active: ""
  datasource:
    url: "jdbc:mysql://localhost:3306/chat-realtime_friend"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 360000 # in seconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      shutdown:
        access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "friend"
    description: "Friend service application"
    version: "1.0.0"