server:
  port: 8081
  servlet:
    context-path: /chat
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: chat-service
  profiles:
    active: ""
  datasource:
    url: "jdbc:mysql://localhost:3306/chat-realtime_chat"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    stream:
      host: localhost
      port: 5672
      username: guest
      password: guest
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: notifications_topics

rabbitmq:
  queue:
    name: chat-message
    json:
      name: chat-message_json
  exchange:
    name: chat-message_exchange
  routing:
    key: chat-message_routing_key
    json:
      key: chat-message_routing_json_key

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "chat"
    description: "Chat service application"
    version: "1.0.0"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 360000 # in seconds